# Set the Python version using the official Nixpacks environment variable
[variables]
NIXPACKS_PYTHON_VERSION = "3.10"

# The start command will be read from the Procfile, so this is not strictly needed
# but it provides clarity.
[start]
cmd = "gradio app.py"
