[phases.setup]
# Install Python, pip, and Git at the system level
nixPkgs = ["python310", "python310Packages.pip", "git"]

[phases.install]
# First, upgrade pip and install build tools, then install requirements
cmds = [
  "python -m pip install --upgrade pip setuptools wheel",
  "python -m pip install -r requirements.txt"
]

[start]
# The command to run the application
cmd = "gradio app.py"
