# Tell Nixpacks we want a Python environment, version 3.10
[providers]
python = "3.10"

# The start command is automatically inferred from the Procfile
# but we can specify it here for clarity.
[start]
cmd = "gradio app.py"
